### BCELoss()

```
CLASS torch.nn.BCELoss(weight=None, size_average=None, reduce=None, reduction='mean')
```

1. reduction
    - mean
    - sum



In [13]:
import torch
import torch.nn as nn
m = nn.Sigmoid()
loss = nn.BCELoss()
input = torch.randn(3,requires_grad=True)
target = torch.empty(3).random_(2)
output = loss(m(input), target)
output.backward()

In [15]:
print(input)
print(target)
print(output)
print(input.grad)

tensor([-0.0858, -1.3066,  0.6027], requires_grad=True)
tensor([0., 0., 0.])
tensor(0.6433, grad_fn=<BinaryCrossEntropyBackward>)
tensor([0.1595, 0.0710, 0.2154])
